name: .NET Build (Windows)

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1

    - name: Setup dotnet SDK
      uses: actions/setup-dotnet@v1.4.0
      with:
        dotnet-version: 3.1.100

    - name: Restore NuGet packages
      run: dotnet restore .\\src\\Solution.sln

    - name: Build with dotnet
      run: dotnet build -c Release .\\src\\Solution.sln

    - name: Run unit tests
      run: dotnet test .\\src\\Solution.sln
